### ISSUE TITLE
DLL load failed while importing _hdfext: 

### ISSUE THREAD

**Issue by qzx-120** [fhs/pyhdf#66]
### What version of pyhdf, HDF4, and Python are you using?

pyhdf version: 0.11.3
HDF4 C library version:
Python version: 3.10

### What operating system are you using?

Windows 10 AMD 64bit

### What did you do?

run this:

from pyhdf.SD import SD, SDC

### What did you expect to see?

no error

### What did you see instead?

Traceback (most recent call last):
  File "C:\Users\Ray\Documents\ACN\read_hdf2.py", line 6, in <module>
    from pyhdf.SD import SD, SDC
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python310\lib\site-packages\pyhdf\SD.py", line 1003, in <module>
    from . import hdfext as _C
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python310\lib\site-packages\pyhdf\hdfext.py", line 10, in <module>
    from . import _hdfext
ImportError: DLL load failed while importing _hdfext: The specified module could not be found.

**Comment by qzx-120** [comment]
i used the wheel from PyPI and it gave me that error.

i reinstalled it using a wheel from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhdf
and it's working fine now.

So i guess it's the wheel in PyPI that has the error.
